### PR TITLE
Issue 230: Remove unused custom packages.

### PR DESCRIPTION
**Pull request by rprevette**
Remove cacti and livecd-tools from packages directory.
Remove apache-webserver kickstart files.

### CODE REVIEW

**Comment by ykhodorkovskiy** [comment]
Are there any artifacts in bootstrap.sh or the top level makefile?

On Mar 1, 2016, at 6:14 PM, rprevette <notifications@github.com<mailto:notifications@github.com>> wrote:


Remove cacti and livecd-tools from packages directory.
Remove apache-webserver kickstart files.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/TresysTechnology/clip/pull/233

Commit Summary

  *   Issue 230: Remove unused custom packages.

File Changes

  *   D kickstart/apache-webserver/Makefile<https://github.com/TresysTechnology/clip/pull/233/files#diff-0> (99)
  *   D kickstart/apache-webserver/README.txt<https://github.com/TresysTechnology/clip/pull/233/files#diff-1> (1)
  *   D kickstart/apache-webserver/apache-webserver.ks<https://github.com/TresysTechnology/clip/pull/233/files#diff-2> (590)
  *   D packages/cacti/Makefile<https://github.com/TresysTechnology/clip/pull/233/files#diff-3> (96)
  *   D packages/cacti/Makefile.tmpl<https://github.com/TresysTechnology/clip/pull/233/files#diff-4> (96)
  *   D packages/cacti/cacti-0.8.8b-1.rf.src.rpm<https://github.com/TresysTechnology/clip/pull/233/files#diff-5> (0)
  *   D packages/cacti/gen-makefile-from-src-rpm.sh<https://github.com/TresysTechnology/clip/pull/233/files#diff-6> (50)
  *   D packages/livecd-tools/Makefile<https://github.com/TresysTechnology/clip/pull/233/files#diff-7> (109)
  *   D packages/livecd-tools/livecd-tools-20.6/API<https://github.com/TresysTechnology/clip/pull/233/files#diff-8> (78)
  *   D packages/livecd-tools/livecd-tools-20.6/AUTHORS<https://github.com/TresysTechnology/clip/pull/233/files#diff-9> (3)
  *   D packages/livecd-tools/livecd-tools-20.6/COPYING<https://github.com/TresysTechnology/clip/pull/233/files#diff-10> (342)
  *   D packages/livecd-tools/livecd-tools-20.6/HACKING<https://github.com/TresysTechnology/clip/pull/233/files#diff-11> (28)
  *   D packages/livecd-tools/livecd-tools-20.6/Makefile<https://github.com/TresysTechnology/clip/pull/233/files#diff-12> (56)
  *   D packages/livecd-tools/livecd-tools-20.6/README<https://github.com/TresysTechnology/clip/pull/233/files#diff-13> (167)
  *   D packages/livecd-tools/livecd-tools-20.6/config/livecd-fedora-minimal.ks<https://github.com/TresysTechnology/clip/pull/233/files#diff-14> (15)
  *   D packages/livecd-tools/livecd-tools-20.6/docs/livecd-creator.pod<https://github.com/TresysTechnology/clip/pull/233/files#diff-15> (117)
  *   D packages/livecd-tools/livecd-tools-20.6/docs/livecd-iso-to-disk.pod<https://github.com/TresysTechnology/clip/pull/233/files#diff-16> (164)
  *   D packages/livecd-tools/livecd-tools-20.6/docs/mkbiarch.8<https://github.com/TresysTechnology/clip/pull/233/files#diff-17> (89)
  *   D packages/livecd-tools/livecd-tools-20.6/imgcreate/__init__.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-18> (68)
  *   D packages/livecd-tools/livecd-tools-20.6/imgcreate/creator.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-19> (947)
  *   D packages/livecd-tools/livecd-tools-20.6/imgcreate/debug.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-20> (92)
  *   D packages/livecd-tools/livecd-tools-20.6/imgcreate/errors.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-21> (58)
  *   D packages/livecd-tools/livecd-tools-20.6/imgcreate/fs.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-22> (659)
  *   D packages/livecd-tools/livecd-tools-20.6/imgcreate/kickstart.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-23> (608)
  *   D packages/livecd-tools/livecd-tools-20.6/imgcreate/live.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-24> (1030)
  *   D packages/livecd-tools/livecd-tools-20.6/imgcreate/util.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-25> (39)
  *   D packages/livecd-tools/livecd-tools-20.6/imgcreate/yuminst.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-26> (236)
  *   D packages/livecd-tools/livecd-tools-20.6/tools/edit-livecd<https://github.com/TresysTechnology/clip/pull/233/files#diff-27> (738)
  *   D packages/livecd-tools/livecd-tools-20.6/tools/livecd-creator<https://github.com/TresysTechnology/clip/pull/233/files#diff-28> (228)
  *   D packages/livecd-tools/livecd-tools-20.6/tools/livecd-iso-to-disk.sh<https://github.com/TresysTechnology/clip/pull/233/files#diff-29> (1456)
  *   D packages/livecd-tools/livecd-tools-20.6/tools/livecd-iso-to-pxeboot.sh<https://github.com/TresysTechnology/clip/pull/233/files#diff-30> (144)
  *   D packages/livecd-tools/livecd-tools-20.6/tools/liveimage-mount<https://github.com/TresysTechnology/clip/pull/233/files#diff-31> (298)
  *   D packages/livecd-tools/livecd-tools-20.6/tools/mkbackup.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-32> (99)
  *   D packages/livecd-tools/livecd-tools-20.6/tools/mkbiarch.py<https://github.com/TresysTechnology/clip/pull/233/files#diff-33> (303)
  *   D packages/livecd-tools/livecd-tools.spec<https://github.com/TresysTechnology/clip/pull/233/files#diff-34> (790)

Patch Links:

  *   https://github.com/TresysTechnology/clip/pull/233.patch
  *   https://github.com/TresysTechnology/clip/pull/233.diff

**Comment by rprevette** [comment]
cacti is in the top level Makefile -- explicitly ignoring it as an excluded
package.

50 |    EXCLUDE_PKGS := examples webpageexample cacti

"cacti" doesn't appear in bootstrap.sh at all.


"apache" doesn't appear in bootstrap.sh or the Makefile

On Tue, Mar 1, 2016 at 6:16 PM, Yuli Khodorkovskiy <notifications@github.com
> wrote:

> Are there any artifacts in bootstrap.sh or the top level makefile?
>
> On Mar 1, 2016, at 6:14 PM, rprevette <notifications@github.com<mailto:

**Comment by ykhodorkovskiy** [comment]
You should remove cacti since there is no longer a package to exclude.

On Mar 1, 2016, at 6:22 PM, rprevette <notifications@github.com<mailto:notifications@github.com>> wrote:

cacti is in the top level Makefile -- explicitly ignoring it as an excluded
package.

50 | EXCLUDE_PKGS := examples webpageexample cacti

"cacti" doesn't appear in bootstrap.sh at all.


"apache" doesn't appear in bootstrap.sh or the Makefile

On Tue, Mar 1, 2016 at 6:16 PM, Yuli Khodorkovskiy <notifications@github.com<mailto:notifications@github.com>
> wrote:

> Are there any artifacts in bootstrap.sh or the top level makefile?
>
> On Mar 1, 2016, at 6:14 PM, rprevette <notifications@github.com<mailto:notifications@github.com><mailto:

**Comment by rprevette** [comment]
"cacti" is now removed from the Makefile

**Comment by minapoli** [comment]
I still see some references to the livecd-tools rpm in both the Makefile and bootstrap.sh. Can you check and see if this is needed for something other than livecd generation? My guess is that those can be removed as well.

**Pull request closed without merging**
